user, 1, 2021-11-05 17:04:11 , 第1行数据插入数据库失败: repo_name:tensorflow(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''C++': '109927937', 'Python': '43242139', 'MLIR': '7068461', 'Starlark': '530966' at line 17")
rails-rails, 0, 2021-11-16 23:22:09 , HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/rails/rails (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028D654AC470>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))网络连接失败: user_name: railsowner_name: rails
rails-rails, 0, 2021-11-16 23:23:02 , HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/rails/rails (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ED69C8C400>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))网络连接失败: user_name: railsowner_name: rails
rails-rails, 0, 2021-11-16 23:24:00 , HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/rails/rails (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E09D6AC470>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))网络连接失败: user_name: railsowner_name: rails
symfony-symfony, 0, 2021-11-23 07:35:18 , HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/symfony/symfony (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))网络连接失败: user_name: symfonyowner_name: symfony
