user, 14295, 2022-02-01 17:39:40 , 第14295号 pr_number: 14335 对应的失败: ('Connection aborted.', TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None))
user, 15344, 2022-02-25 19:18:44 , 第15344号 pr_number: 15394 对应的失败: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/django/django/pulls/15394/files?per_page=100&page=1 (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)'))))
