user, 38768, 2022-01-01 09:18:10 , 第38768号 pr_number: 64304 对应的失败: tuple index out of range
user, 43813, 2022-01-01 19:49:26 , 第43813号 pr_number: 72201 对应的失败: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/kubernetes/kubernetes/pulls/72201/files?per_page=100&page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000146BAE9C940>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
user, 57471, 2022-01-02 04:33:14 , 第57471号 pr_number: 92838 对应的失败: ('Connection aborted.', TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None))
